version: '3.8'

services:
  frontend:
    image: eliezerperl/frontend
    build: ./frontend
    ports:
      - 5173:5173
  backend:
    image: eliezerperl/backend
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - DB_URL=mongodb+srv://eliezerrules:irock2009@amazonclus.7uqmpuf.mongodb.net/amazondb?retryWrites=true&w=majority
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - amazon:/data/db
volumes:
  amazon: 