const GET_REQUEST = 'GET_REQUEST';
const GET_SUCCESS = 'GET_SUCCESS';
const GET_FAIL = 'GET_FAIL';

const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNOUT = 'USER_SIGNOUT';

const UPDATE_CART = 'UPDATE_CART';

const SAVE_SHIPPING_ADDRESS = 'SAVE SHIPPING_ADDRESS';

export {
  GET_FAIL,
  GET_SUCCESS,
  GET_REQUEST,
  USER_SIGNIN,
  USER_SIGNOUT,
  UPDATE_CART,
  SAVE_SHIPPING_ADDRESS,
};
