const GET_REQUEST = 'GET_REQUEST';
const GET_SUCCESS = 'GET_SUCCESS';
const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
const GET_FAIL = 'GET_FAIL';

const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNOUT = 'USER_SIGNOUT';

const UPDATE_CART = 'UPDATE_CART';
const CLEAR_CART = 'CLEAR_CART';

const SAVE_SHIPPING_ADDRESS = 'SAVE SHIPPING_ADDRESS';
const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';

export {
  GET_FAIL,
  GET_SUCCESS,
  GET_SEARCH_SUCCESS,
  GET_REQUEST,
  USER_SIGNIN,
  USER_SIGNOUT,
  UPDATE_CART,
  CLEAR_CART,
  SAVE_SHIPPING_ADDRESS,
  SAVE_PAYMENT_METHOD,
};
